# Generated by Django 5.1 on 2024-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquest',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aiquest',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
