# Generated by Django 5.1 on 2024-08-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cool_todo', '0001_initial'), ('cool_todo', '0002_product'), ('cool_todo', '0003_alter_product_price')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'Product',
                'managed': True,
            },
        ),
    ]
